name: 'install-action'
description: 'GitHub action to get & install WasmVM'
inputs:
  token:
    description: 'GitHub API token'
    required: true
  version:
    description: 'Release version'
    required: false
  dev:
    description: 'Is dev package?'
    required: true
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'