name: 'install-action'
description: 'GitHub action to get & install WasmVM'
inputs:
  version:
    description: 'Release version'
    required: false
    default: 'RELEASE.md'
runs:
  using: 'node20'
  main: 'dist/index.js'