name: Test

on:
  push:
    branches:
      - test

jobs:
  ubuntu:
    name: Test Ubuntu
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test action
      uses: ./
      with:
        token: ${{secrets.GITHUB_TOKEN}}
  
  macos:
    name: Test MacOS
    runs-on: [macos-14]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test action
      uses: ./
      with:
        token: ${{secrets.GITHUB_TOKEN}}